"""Write scraped DTU Learn data into the Obsidian vault.

- `<course>/announcements.md`: every announcement as Markdown, newest first (regenerated).
- `<course>/backlog.md`: upcoming assignment deadlines added under `## Next`, moved deadlines updated.
- `out/<course>/videos.md`: video links found in the course (synced into material/learn/ like other files).

The course folder is derived from the sync destination `<course>/material/learn`.
"""

from __future__ import annotations

import json
import re
from datetime import date, datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import html2text

CPH = ZoneInfo("Europe/Copenhagen")
MARK = "<!-- learn:dropbox:{ou}:{id} -->"
VIDEO_RE = re.compile(
    r"https?://(?:www\.)?(?:youtube\.com/(?:watch|playlist|embed)[^\s\"'<>\\]*|youtu\.be/[^\s\"'<>\\]+"
    r"|video\.dtu\.dk/[^\s\"'<>\\]+|[\w.-]*panopto[\w.-]*/[^\s\"'<>\\]+|[\w.-]*kaltura[\w.-]*/[^\s\"'<>\\]+"
    r"|[\w.-]*zoom\.us/rec/[^\s\"'<>\\]+|vimeo\.com/[^\s\"'<>\\]+)"
)


def course_folder(dest: Path) -> Path | None:
    return dest.parent.parent if dest.name == "learn" and dest.parent.name == "material" else None


def vault_root(p: Path) -> Path | None:
    return next((a for a in [p, *p.parents] if (a / ".obsidian").is_dir()), None)


def local(ts: str | None) -> datetime | None:
    if not ts:
        return None
    return datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone(CPH)


def to_md(html: str) -> str:
    h = html2text.HTML2Text()
    h.body_width = 0
    h.ignore_images = True
    return re.sub(r"\n{3,}", "\n\n", h.handle(html or "")).strip()


def set_updated(text: str) -> str:
    return re.sub(r"(?m)^updated: .*$", f"updated: {date.today().isoformat()}", text, count=1)


def without_updated(text: str) -> str:
    return re.sub(r"(?m)^updated: .*$", "", text, count=1)


# ---------------------------------------------------------------- announcements


def write_announcements(src: Path, course: Path, title: str) -> int:
    """Regenerate <course>/announcements.md. Returns number of announcements, 0 if unchanged."""
    news_path = src / "announcements" / "news.json"
    if not news_path.exists():
        return 0
    items = sorted(json.loads(news_path.read_text()), key=lambda x: x.get("StartDate") or "", reverse=True)
    if not items:
        return 0
    root = vault_root(course)
    learn = (course / "material" / "learn").relative_to(root) if root else Path("material/learn")
    parts = [
        "---\ntype: reference\nsource: DTU Learn\n"
        f"updated: {date.today().isoformat()}\n---\n\n"
        f"# {title}: DTU Learn announcements\n\n"
        "Generated by `~/code/dtu/dtu-learn-sync` (`sync`). Do not edit: the file is rewritten on every sync. "
        "Newest first.\n"
    ]
    for it in items:
        when = local(it.get("StartDate"))
        stamp = when.strftime("%Y-%m-%d %H:%M") if when else "undated"
        body = to_md((it.get("Body") or {}).get("Html") or "") or (it.get("Body") or {}).get("Text", "")
        parts.append(f"\n## {stamp} · {it['Title'].strip()}\n\n{body}\n")
        for a in it.get("Attachments", []):
            parts.append(f"- Attachment: [[{learn}/announcements/{it['Id']}/{a['FileName']}|{a['FileName']}]]\n")
    text = "".join(parts)
    target = course / "announcements.md"
    if target.exists() and without_updated(target.read_text()) == without_updated(text):
        return 0
    target.write_text(text)
    return len(items)


# ---------------------------------------------------------------- deadlines


def update_backlog(src: Path, course: Path, ou: int) -> list[str]:
    """Add upcoming assignment deadlines to <course>/backlog.md under ## Next."""
    folders_path, backlog = src / "assignments" / "folders.json", course / "backlog.md"
    if not folders_path.exists() or not backlog.exists():
        return []
    text = backlog.read_text()
    lower = text.lower()
    now = datetime.now(timezone.utc)
    changes, new_lines = [], []
    for f in json.loads(folders_path.read_text()):
        due = local(f.get("DueDate"))
        mark = MARK.format(ou=ou, id=f["Id"])
        due_txt = due.strftime("%Y-%m-%d %H:%M") if due else None
        if mark in text:
            line = next(l for l in text.splitlines() if mark in l)
            m = re.search(r"deadline \*\*([^*]+)\*\*", line)
            if due_txt and m and m.group(1) != due_txt:
                text = text.replace(line, line.replace(m.group(0), f"deadline **{due_txt}**"))
                changes.append(f"Deadline moved: {f['Name']} -> {due_txt}")
            continue
        if not due or due < now:
            continue
        prefix = re.split(r":| - ", f["Name"])[0].strip().lower()
        if f["Name"].strip().lower() in lower or (prefix in lower and due.strftime("%Y-%m-%d") in lower):
            continue  # already tracked by hand
        new_lines.append(
            f"- [ ] **{f['Name'].strip()}** *(execute · {date.today().isoformat()})* "
            f"DTU Learn deadline **{due_txt}**. {mark}"
        )
        changes.append(f"Deadline added: {f['Name']} ({due_txt})")
    if new_lines:
        m = re.search(r"(?ms)^## Next\s*\n(.*?)(?=^## |\Z)", text)
        if not m:
            return []
        section = m.group(1).rstrip("\n")
        text = text[: m.start(1)] + (section + "\n" if section else "") + "\n".join(new_lines) + "\n\n" + text[m.end(1):]
    if changes:
        backlog.write_text(set_updated(text))
    return changes


# ---------------------------------------------------------------- videos


def write_videos(src: Path) -> int:
    urls: dict[str, str] = {}
    for f in [src / "content" / "toc.json", src / "announcements" / "news.json", src / "assignments" / "folders.json"]:
        if f.exists():
            for u in VIDEO_RE.findall(f.read_text().replace("&amp;", "&")):
                urls.setdefault(u.rstrip(".,;:)"), f.parent.name)
    out = src / "videos.md"
    if not urls:
        out.unlink(missing_ok=True)
        return 0
    lines = ["# Video links\n\nFound in course content, announcements and assignments.\n\n"]
    lines += [f"- {u} ({where})\n" for u, where in sorted(urls.items())]
    out.write_text("".join(lines))
    return len(urls)


def update_course(src: Path, dest: Path, ou: int, title: str) -> list[str]:
    course = course_folder(dest)
    if not course or not course.exists():
        return []
    notes = []
    n = write_announcements(src, course, title)
    if n:
        notes.append(f"announcements.md rewritten ({n} announcements)")
    notes += update_backlog(src, course, ou)
    return notes
